name: CI (Build and Push Docker Image)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Specify the version to use'
        required: true
      server:
        description: 'Specify the server to use'        
        required: true
        type: choice
        options:
          - dev
          - sandbox


jobs:
  deploy:
    uses: ./.github/workflows/template.yml
    with:
      service_name: app
      version: ${{ github.event.inputs.version }}
      server: ${{ github.event.inputs.server }}
      base_path: test
